on: push
name: CI
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4']
        composer: ['--prefer-lowest', ' ']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: "cs2pr"

    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v3"
      with:
        path: "~/.composer/cache"
        key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

    - name: "Composer"
      run: "composer update ${{ matrix.composer }} --prefer-stable"

    - name: "PHPUnit"
      run: "php vendor/bin/phpunit"

  phpcs:
    name: PHP Codesniffer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: "cs2pr"

    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v3"
      with:
        path: "~/.composer/cache"
        key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

    - name: "Composer"
      run: "composer update ${{ matrix.composer }} --prefer-stable"

    - name: "phpcs"
      run: "vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr"

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composer: ['--prefer-lowest', ' ']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        tools: "cs2pr"

    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v3"
      with:
        path: "~/.composer/cache"
        key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

    - name: "Composer"
      run: "composer update ${{ matrix.composer }} --prefer-stable"

    - name: "Psalm"
      run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=4"
